title: "Mon Site Jekyll"
description: "Un exemple de site Jekyll hébergé sur GitHub Pages."
baseurl: "/Virtualescola66" # Remplacez par le nom de votre dépôt
url: "https://Virtualescola66.github.io" # Remplacez par votre nom d'utilisateur GitHub
